# Generated by Django 2.1.7 on 2019-05-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='front_page',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
