# Generated by Django 2.1.7 on 2019-05-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_books_front_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='more_info',
            field=models.TextField(blank=True),
        ),
    ]
